### ISSUE TITLE
Allow building language packs for all projects at once

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#104]
As suggested in #95, being able to run `wp traduttore build --all` could be useful in certain cases.

**Comment by grappler** [comment]
When running the command it gives a big block of text but it is not clear from the ID which language the language pack ist and to which project it belongs to.

I started to experiment with add the local `(ID: 3, Locale: fr)` but I am not sure what is the best way of structuring the output.

```
wp @translate traduttore project build --all
No language pack generated for translation set as there were no changes (ID: 3)
No language pack generated for translation set as there were no changes (ID: 1)
Language pack generated for translation set (ID: 7)
No language pack generated for translation set as there were no changes (ID: 14)
No language pack generated for translation set as there were no changes (ID: 5)
Language pack generated for translation set (ID: 10)
Success: Language pack generation finished
```

**Comment by swissspidy** [comment]
We could use a progress bar and only show warnings/errors, maybe together with the project ID. Not urgent though IMO.

**Comment by grappler** [comment]
Not urgent but should be documented that I was I mentioned it.

**Comment by ocean90** [comment]
Created a new issue for the output: https://github.com/wearerequired/traduttore/issues/146
