### ISSUE TITLE
Support Gutenberg (JavaScript I18N)

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#12]
It would be great if we could automatically create the additional POT file if https://github.com/WordPress/packages/tree/master/packages/babel-plugin-makepot is being used or at least make it so that we can merge the generated POT file with an existing one.

For the latter option, we'd need a way for plugins to tell Traduttore where to find that POT file (config file?) unless we want to scan the whole directory first for existing POT files.

**Comment by swissspidy** [comment]
The `--merge` option is now available for `wp i18n make-pot` 🎉 

JavaScript extraction (with the option to skip this step) is coming soon.

This means we can build Gutenberg blocks using modern ECMAScript and Babel, and then use `wp i18n make-pot --merge=<optional-path-to-pot-file>` in Traduttore to get the strings from there.

My suggestion is to use a configuration file, let's call it `.traduttore.json`, to support this.

An example configuration file for the plugin `foo-plugin` could look like this:

```json
{
  "mergeWith": "languages/extracted-strings-from-js.pot",
  "textDomain": "foo",
}
```

`mergeWith` (or just `merge`) is obviously useful when you have an existing POT file.

`textDomain` (or just `domain`) could be useful when the plugin's repository name differs from the text domain (e.g. underscores, or uppercase chars).

A possible third option could be `exclude` that allows excluding/ignoring specific files and folders that shouldn't be scanned. Useful for third-party libs and stuff like that.

A configuration file is also future-proof in the sense that we can support more `wp i18n make-pot` arguments whenever they appear, and also support some things that are specific to Traduttore / GlotPress.

The workflow would be as follows:

1. Receive incoming webhook from GitHub
1. Clone repository
1. Check for existence of `.traduttore.json`
1. Call `wp i18n make-pot` with the options from the config file.  
  Example: `wp i18n make-pot --exclude=<exclude> --domain=<textDomain> --merge=<mergeWith>`
1. Optional: in case we ever have Traduttore-specific configs, we could also cache these as metadata in the database.

@ocean90 Thoughts?

**Comment by ocean90** [comment]
I don't think we need the dot in `traduttore.json`. Would extending the `composer.json` an option too? Why would you want to cache the metadata?

Otherwise it sounds good.

**Comment by swissspidy** [comment]
> I don't think we need the dot in `traduttore.json`.

The main benefit would be that this way the config file will be naturally grouped with other config files whose name starts with dots.

> Would extending the `composer.json` an option too? 

We could support both, in case a project does not use Composer. Composer has an `extra` property that can be extend for such cases. Example:

```json
{
  "extra": {
    "traduttore": {
      "mergeWith": "languages/extracted-strings-from-js.pot",
      "textDomain": "foo",
    }
  }
}
```

> Why would you want to cache the metadata?

In case we ever want to expose these warnings in GlotPress itself, we could store the warnings in the database (project meta) and then load them from there.

It's not something I would add in the initial implementation, it was more about mentioning that it's possible.

**Comment by swissspidy** [comment]
I think we can support more if not all options `wp i18n make-pot` takes:

```json
{
  "mergeWith": "languages/extracted-strings-from-js.pot",
  "textDomain": "foo",
  "source": "inc/",
  "exclude": [ "assets", "foo" ],
  "skipJs": true
}
```

* `textDomain: null` could equal to `--ignore-domain` in WP-CLI.  
  Alternatively, we can add an `ignoreDomain` option
* `source`: In case one uses a repository where the plugin/theme is in a subfolder or something.
