### ISSUE TITLE
Allow to filter/set a custom path/URL for language packs

### ISSUE THREAD

**Issue by ocean90** [wearerequired/traduttore#121]
`ZipProvider::get_zip_url()`, `ZipProvider::get_zip_path()`, and `ZipProvider::get_cache_dir()` are using `WP_CONTENT_DIR` / `WP_CONTENT_URL` and the directory `traduttore` by default. There's currently no easy way to change that for example if you want to store the files on another mounting point of your disk and/or want to use a custom domain for the downloads.

**Comment by swissspidy** [comment]
Sounds like adding two filters would suffice, e.g. `traduttore.content_dir` and `traduttore.content_url`.
