### ISSUE TITLE
WP-CLI Project Update command does not add VCS type and Repo URL

### ISSUE THREAD

**Issue by grappler** [wearerequired/traduttore#125]
**Issue Overview**
When running `wp traduttore project update 17` the VCS type and Repo URL are not updated when viewing it in `wp traduttore project info 17`

**To Reproduce**
1. Run `wp traduttore project update 17`
2. Run `wp traduttore project info 17`
3. See that the  VCS type and Repo URL are still unknown

**Expected behavior**
 VCS type and Repo URL should be updated like when the request to the route is made.

**Screenshots**
![image](https://user-images.githubusercontent.com/1785641/48427615-6fea2b80-e769-11e8-8145-341c483aa20c.png)

**Comment by swissspidy** [comment]
Hmm not so sure about that 😕 

When we receive an incoming webhook we can be pretty sure about VCS type, repo URL, visibility, etc.

If all that information is missing and you run `wp traduttore project update`, we can only guess that data.

**Comment by grappler** [comment]
Just for documentation. The following information are only provided from the GitHub webhook.
```
Repository URL:		(unknown)
Repository VCS Type:	(unknown)
```
