### ISSUE TITLE
Empty language pack ZIP

### ISSUE THREAD

**Issue by florianbrinkmann** [wearerequired/traduttore#168]
**Issue Overview**
After already playing around with Traduttore some time ago, I gave it a try again today and had a problem with empty language pack ZIPs. After some debugging I found out that the issue was the `.tmp` ending of the temporary ZIP file with the `ZipArchive::CREATE`.

https://github.com/wearerequired/traduttore/blob/3.0.0/inc/ZipProvider.php#L150-L152

It worked when I either created a `$temp_zip_file` with `.zip` ending or changed the `CREATE` to `OVERWRITE`.

My first try with Traduttore was on the same server, and it worked back then, so it is a little bit strange.

**To Reproduce**
In my case: run the `wp traduttore language-pack build` WP CLI command and the generated ZIP is empty.

**Versions**

* PHP: 7.3.11
* WP-CLI: 2.4.0
* GlotPress: 2.3.1
* WordPress: 5.3.2

**Comment by ocean90** [comment]
Thanks for the report! Can you check what [error code ](https://www.php.net/manual/en/ziparchive.open.php#refsect1-ziparchive.open-returnvalues)`$zip->open()` is returning?

**Comment by florianbrinkmann** [comment]
Yes, it returns the Code `19`. Reading the comments on the php.net site, that is `Not a zip archive`.
