### ISSUE TITLE
There are some problems with the current documentation

### ISSUE THREAD

**Issue by sunxiyuan** [wearerequired/traduttore#177]
My English is not very good, so I try to describe the problem in this issue as much as possible, instead of submitting a pr to fix this problem.

Problem one:
Should it be stated in the installation method that if you install by github clone, you need to execute composer install to install dependencies

Problem two:
It may be necessary to explain access in the API documentation:https://<home_url>/api/translations/my-project API "home_url" needs to include the URL prefix of GlotPress.

I don't know if I described it clearly, but I was stuck on these two issues for several days, and finally checked the source code to find the problem.

**Comment by ocean90** [comment]
Hello @sunxiyuan, thanks for the clear feedback!

Our [contributing section](https://github.com/wearerequired/traduttore/blob/master/CONTRIBUTING.md#contributing-code) includes a step for the `composer install` part. Did you use another guide for the installation?

The missing GlotPress prefix is definitely something we should add to https://github.com/wearerequired/traduttore/blob/master/docs/plugin-theme.md#example.

**Comment by sunxiyuan** [comment]
I am referring to: https://wearerequired.github.io/traduttore/installation.html
There is such a paragraph:
> Installing Traduttore
> If you’re using Composer to manage dependencies, you can use the following command to add the plugin to your site:
> 
> composer require wearerequired/traduttore
> Alternatively, you can download a ZIP file containing the plugin on GitHub and upload it in your WordPress admin screen.
> 
> **Afterwards, activating Traduttore is all you need to do. There’s no special settings UI or anything for it.**

Please note the part I marked in bold, he said that it can be directly enabled after clone from github.
I was misled by this sentence
