### ISSUE TITLE
Use PHPStan for Static Analysis

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#189]
**Issue Overview**

Something like https://packagist.org/packages/szepeviktor/phpstan-wordpress or even just PHPStan directly with custom stubs will be very useful for finding issues in the codebase using static analysis.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**

* Browser: 
* PHP: 
* WP-CLI: 
* GlotPress: 
* WordPress: 

**Additional context**

**Comment by szepeviktor** [comment]
> even just PHPStan directly with custom stubs

😿

**Comment by swissspidy** [comment]
@szepeviktor Feels like you have your eyes everywhere 😄 

Since this repo requires PHP 7.1+ I think there's no reason not to use your package directly 🙂

**Comment by szepeviktor** [comment]
> Feels like you have your eyes everywhere 😄

Goole Alerts

![kép](https://user-images.githubusercontent.com/952007/94910989-c10e8000-04a5-11eb-9439-2ee51cc986e1.png)

**Comment by szepeviktor** [comment]
> Since this repo requires PHP 7.1+

I keep mine matched to PHPStan `"php": "^7.1|^8.0"`

https://github.com/phpstan/phpstan/blob/83bc73c6972bb4dabc7e543656c25aad68b0fa05/composer.json#L5-L7

**Comment by swissspidy** [comment]
Yup, I meant the Traduttore repo requires 7.1+, so it's a nice fit.

**Comment by swissspidy** [comment]
@ocean90 Wanna run this on Travis too?

**Comment by szepeviktor** [comment]
LGTM https://github.com/wearerequired/traduttore/pull/191
