### ISSUE TITLE
Translation version when updating translation in glotpress

### ISSUE THREAD

**Issue by kimmenbert** [wearerequired/traduttore#214]
**Issue Overview**
We're using Traduttore only to get the API endpoint needed to install translations from custom glotpress installation trough composer using inpsyde/wp-translation-downloader

Finally got this working ok, translation got installed from our custom glotpress. But when we're making updates to the translations in glotpress, no version update gets triggered. Based on your code I see that this probably only happens when integrated to github / bitbucket etc.

Do you have any idea how we could bump versions when doing edits in glotpress?

**To Reproduce**
1. Make a project with a translation
2. Do a GET request to /api/translations/PROJECTSLUG
3. See version 1.0
4. Make changes to the translation in glotpress
5. Repeat from step 2.

**Expected behavior**
I don't really expect this to work, since it doesn't seem like the main goal of traduttore.

**Versions**
Traduttore: 3.1.0
GlotPress: 2.3.1
WordPress: 5.7.1

**Comment by ocean90** [comment]
Hello there, the version you're seeing there is the version of the plugin/theme. Translations don't have a specific version. So unless you update the version of the plugin/theme the `version` field doesn't change on translation changes.
The only thing that changes is the `updated` field which is used [to compare your local translation files to check for updates](https://github.com/wearerequired/traduttore-registry/blob/4050ecd0c5ace3793ce6f764944519e50d0ccedf/inc/namespace.php#L95-L102).
