### ISSUE TITLE
Support PHP 8+ development environments

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#237]
**Issue Overview**

Due to the `"phpunit/phpunit": "^7.5.20",` version constraint (and perhaps also others) it's not currently possible to install dependencies on PHP 8.1

Using https://github.com/Yoast/wp-test-utils might be an easy way to solve this.

**To Reproduce**

Try to install dependencies and run tests on PHP 8 or 8.1

**Expected behavior**

I should be able to install dependencies and run tests on PHP 8+

**Screenshots**

**Versions**

* Browser: 
* PHP: 8.1
* WP-CLI: 
* GlotPress: 
* WordPress: 

**Additional context**

**Comment by ocean90** [comment]
I'm okay with bumping the PHP requirement to 8.1 based on https://www.php.net/supported-versions.php.
