### ISSUE TITLE
Avoid Slack notifications for imports without changes

### ISSUE THREAD

**Issue by ocean90** [wearerequired/traduttore#35]
When nothing has changes you get the following notification:

> Project Name: *0* new strings were added, *0* were fuzzied, and *0* were obsoleted. There were *0* errors

IMO we should suppress such messages in https://github.com/wearerequired/traduttore/blob/0e9e7f63d4a13a6e626be4f9ee2da525e8325a59/inc/Plugin.php#L112-L130.

**Comment by swissspidy** [comment]
Looks like returning `false` in that callback avoids sending anything.

I guess it makes sense. When you push lots of commits without any changes, it can become quite noisy. On the other hand, it lets you know that the service is still working properly.

**Comment by grappler** [comment]
This does not seem to be fixed. 
![image](https://user-images.githubusercontent.com/1785641/42437274-e30b1604-835c-11e8-8830-7b6931937466.png)

**Comment by swissspidy** [comment]
Well we'd need to make use of the new `traduttore_updated_from_github_send_notification`filter in our [required-glotpress](https://github.com/wearerequired/required-glotpress) plugin.

**Comment by ocean90** [comment]
@grappler Are you sure that you are using 2.0.3 which was just released seconds ago?
