### ISSUE TITLE
Document available actions/filters

### ISSUE THREAD

**Issue by ocean90** [wearerequired/traduttore#39]
* `traduttore_zip_generated`
* `traduttore_updated_from_github`
* #38 

Not sure if the readme would be the right place for this. It already has a lot of information. Maybe we should start splitting the file into a /docs directory?

**Comment by swissspidy** [comment]
The default themes for GitHub pages can be found here: https://pages.github.com/themes/

**Comment by ocean90** [comment]
https://docsify.js.org/#/?id=docsify looks promising.

**Comment by swissspidy** [comment]
Cool. I‘ll give it a go.

**Comment by swissspidy** [comment]
https://docusaurus.io/en/ looks interesting too.

**Comment by swissspidy** [comment]
Gave Docusaurus a go this last weekend. It was pretty straightforward to set up and the result is quite good without any customizations made.

It even allows updating the docs page (which we can host via GitHub pages) automatically via Travis CI.

I think we should give it a go. Happy to write some documentation too :-)
