### ISSUE TITLE
Bust WP-CLI translation cache

### ISSUE THREAD

**Issue by grappler** [wearerequired/traduttore#4]
I updated the translations on translate.required.com but WP-CLI is not downloading the latest version.

```
wp @stage language core update
Updating 'German' translation for Swisscom Post Types ...
Using cached file '/home/deploy/.wp-cli/cache/translation/plugin-swisscom-content-types--de_DE-1522156473.zip'...
Entpacken der aktualisierten Version …
Die aktuelle Version wird installiert …
Die Übersetzung wurde erfolgreich aktualisiert.
Success: Updated 1/1 translations.
```

**Comment by swissspidy** [comment]
WP-CLI uses the `updated` field for the cache file name, so we should be good:

https://github.com/wp-cli/language-command/blob/df9b925146b3ebf61fa1aae237f87392c79215fe/src/WP_CLI/LanguagePackUpgrader.php#L59
