### ISSUE TITLE
Traduttore as a Service (TaaS)

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#54]
After successfully giving a talk about WordPress I18N Workflows, telling everyone how great Traduttore is. I even promoted it as "WordPress.org for everyone". After that, I wondered: how can we make this statement really true? How can we make it easier for people to use this?

Setting up Traduttore requires quite some technical knowledge, so I doubt many people or agencies will use it out of the box. There's only so much we can do with better documentation and UI changes either.

What if we built some simple Multisite solution where everyone can create their own Traduttore instance, connecting their private plugins and using this platform to translate them?

It would truly be (translate.)WordPress.org for everyone. Kinda what platforms like Transifex & co. do, but really tailored to the WordPress community.

**Comment by swissspidy** [comment]
Some thoughts after a quick chat yesterday:

* Traduttore's main selling point is the language pack API, which is quite trivial.  
  What if we somehow offered integrations with Transifex and other platforms (perhaps even a self-hosted GlotPress install) so people can use them _and_ Traduttore together?
* A GitHub application could be very useful (see #55) to lower the barriers.

**Comment by grappler** [comment]
I think this may be best discussed in a Wiggly post as it is not related to the code.

**Comment by KarinChristen** [comment]
Domain traduttore.pro wurde gekauft: https://secure.helpscout.net/conversation/803037073/31046?folderId=330336

**Comment by swissspidy** [comment]
Interesting: https://translationspress.com/
