### ISSUE TITLE
JSON Translation Files for WordPress 5.0

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#62]
Let's follow progress at https://core.trac.wordpress.org/ticket/45103 and https://meta.trac.wordpress.org/ticket/3875 to see what we can do in Traduttore to support that.

Right now it looks like we have to create files like `{$domain}-{$locale}-{$md5}.json` where `$md5` is the MD5 hash of the JS file path.

**Comment by swissspidy** [comment]
The first iteration in core has now landed: https://core.trac.wordpress.org/changeset/43825

**Comment by swissspidy** [comment]
Note: Like on dotorg, JS-only strings shouldn't be included in MO files and vice-versa.

**Comment by ocean90** [comment]
Current implementation on w.org can be seen in https://meta.trac.wordpress.org/changeset/7833.
