### ISSUE TITLE
Make cron event times filterable

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#66]
In #3 the time we wait until the next ZIP file generation has been reduced to 5 minutes.

I get it that one doesn't want to wait 15 minutes all the time, but when lots of translations are happening, it gets noisy quickly:

<img width="513" alt="screenshot 2018-10-24 at 10 34 51" src="https://user-images.githubusercontent.com/841956/47417586-96bfce00-d778-11e8-81ea-bf7ba05cbac1.png">

Can we somehow prevent this by throttling notifications or changing the time again? For the latter I suggest making them filterable. Both for the incoming webhook event as well as the language pack generation.

**Comment by swissspidy** [comment]
I thought about that too, but it won‘t directly solve the issue described in the screenshot, does it?

Another thought: enable people to set up a fixed cron event instead and disable these single events.

**Comment by ocean90** [comment]
It depends, it would delay the the build until there was no new translation 5 minutes after the last change. Based on the screenshot the builds seem to be nearly every 5 minutes so I think the solution would have reduced the builds.

Fwiw: translate.w.org uses 30 minutes.

**Comment by swissspidy** [comment]
Let‘s do this then and add some filters as well.

In the same swoop I can also improve docs for all the cron things.
