### ISSUE TITLE
Add CLI command for debugging

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#67]
Some thoughts about possible WP-CLI commands for easier debugging:

## `wp traduttore info`

This could show some status information, e.g. things like:

* Plugin version
* Path to git binary
* Path to WP-CLI binary
* Path to cache dir
* Whether requirements (git, WP-CLI i18n-command, zip extension, Slack plugin, etc.) are met
* …?

## `wp traduttore debug <project>`

* Repository information (type, vcs type, url, visibility)
* Path to the cached repository
* Whether the repository exists and Traduttore has access to it

**Comment by ocean90** [comment]
More thoughts:

> wp traduttore debug `<project>`

* Timestamp/status of last import
* Available language packs maybe with their last build time

**Comment by swissspidy** [comment]
> Available language packs maybe with their last build time

So sort of like the API endpoint?

Maybe we could use a separate command for that to show a proper list with different `--format` options.

**Comment by swissspidy** [comment]
> Timestamp/status of last import

I don't think we store that information yet. We store the last build date for language packs, but nothing for the import. Unless GlotPress does that ...?
