### ISSUE TITLE
CLI: Insufficient argument validation

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/traduttore#95]
**Issue Overview**

Right now it's possible to run `wp traduttore build` or `wp traduttore update` without specifying a project.

In this case `$args[0]` is `null` and `$project` turns out to be some global one or something.

This should not be supported.

**To Reproduce**
1. Run `wp traduttore build`
2. Notice that ZIP files are generated for some random translation set

**Expected behavior**
An error message because no valid project has been passed.

**Comment by grappler** [comment]
It would be good to have a `wp traduttore build --all`.  After https://github.com/wearerequired/traduttore/pull/13 some projects are missing translations builds are they were made before the new feature was introduced.

**Comment by swissspidy** [comment]
After all projects are updated accordingly to include the ZIP build time, is such a flag still useful?

**Comment by grappler** [comment]
Maybe if all of the translation zip files got deleted and need to be regenerated.
